language: php
php:
  - 7.3
services:
  - docker

before_script:
  - make build

script: /vendor/bin/phpunit --exclude-group='disabled' --log-junit build/test_results/phpunit/junit.xml tests

notifications:
    email:
        - josecarlosduran@gmail.com

